In [53]:
li = [3, 56, 2, 7, 8]
sq = [x * x for x in li]
sq

[9, 3136, 4, 49, 64]

In [9]:
sq = [x * x if x % 2 == 0 else x * x * x for x in li]
sq

[27, 3136, 4, 343, 64]

In [55]:
st_li = sorted(li, key = lambda x : x % 2 == 0)
st_li

[3, 7, 56, 2, 8]

In [10]:
import numpy as np

In [11]:
I = np.eye(3,3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
ran = np.random.randint(1, 100, (1, 100))
ran

array([[88, 12, 26, 24, 54, 23, 45,  8, 81, 21,  6, 77, 90, 45, 99, 38,
        32,  2,  7, 72, 63, 26, 39,  1,  6, 51, 67, 39, 71, 62, 63, 38,
        75, 98, 92, 87,  9, 70, 90, 49, 38, 99,  9, 40, 19, 17, 27, 17,
        87, 60, 64, 39, 49, 14, 30, 36, 10, 12, 78, 74, 87, 75, 99, 77,
        71, 21, 72, 55, 20, 72, 41, 46, 14, 39, 52, 82, 23, 99, 81, 31,
        25, 91, 14, 22, 20, 67, 32, 35, 83, 50, 57, 37,  7, 20, 47, 80,
        49, 19, 99, 62]])

In [16]:
import seaborn as sns

df = sns.load_dataset('titanic')
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [20]:
df[(df['sex'] == 'female') & (df['age'] > 30)]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
15,1,2,female,55.0,0,0,16.0000,S,Second,woman,False,NaN,Southampton,yes,True
18,0,3,female,31.0,1,0,18.0000,S,Third,woman,False,NaN,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
862,1,1,female,48.0,0,0,25.9292,S,First,woman,False,D,Southampton,yes,True
865,1,2,female,42.0,0,0,13.0000,S,Second,woman,False,NaN,Southampton,yes,True
871,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False

In [21]:
import pandas as pd

In [46]:
df.groupby('sex')[['age', 'fare', 'survived']].mean()

              age       fare  survived
sex
female  27.915709  44.479818  0.742038
male    30.726645  25.523893  0.188908

In [5]:
def grad(x):
    return 2 * x
    # return 3 * (x ** 2)

x = 4
path = [x]
steps = 20

lr = 0.1
for i in range(steps):
    g = x - (lr * grad(x))
    path.append(g)
    x = g
path

[4,
 3.2,
 2.56,
 2.048,
 1.6384,
 1.31072,
 1.0485760000000002,
 0.8388608000000002,
 0.6710886400000001,
 0.5368709120000001,
 0.4294967296000001,
 0.3435973836800001,
 0.27487790694400005,
 0.21990232555520003,
 0.17592186044416003,
 0.140737488355328,
 0.11258999068426241,
 0.09007199254740993,
 0.07205759403792794,
 0.057646075230342354,
 0.04611686018427388]

In [ ]:
def reverse(head):
    n = head
    while n.next:
        temp = n.next
        n = n.next
    last
    while n.next:
        n

In [ ]:
stack = []
stack.append()
stack.pop()

In [ ]:
import dequeu

In [ ]:
create table Employees(
    emp_id INT,
    name VARCHAR(20),
    constraint dep_id FORIEGN KEY (dep_id) REFERENCES Department(dep_id)
)

create table Department(
    dep_id INT,
    manager_id INT,
    name VARCHAR(20)
)