In [1]:
import pandas as pd
df = pd.read_csv('/home/nihal_farooq_m/Bro_Files/Week 16/ChatGPT/Pendings/Employers_data.csv')
df

,Employee_ID,Name,Age,Gender,Department,Job_Title,Experience_Years,Education_Level,Location,Salary
0,1,Merle Ingram,24,Female,Engineering,Engineer,1,Master,Austin,90000
1,2,John Mayes,56,Male,Sales,Executive,33,Master,Seattle,195000
2,3,Carlos Wille,21,Male,Engineering,Intern,1,Bachelor,New York,35000
3,4,Michael Bryant,30,Male,Finance,Analyst,9,Bachelor,New York,75000
4,5,Paula Douglas,25,Female,HR,Analyst,2,Master,Seattle,70000
...,...,...,...,...,...,...,...,...,...,...
9995,9996,Thomas Rossin,51,Male,Sales,Executive,28,Master,Austin,185000
9996,9997,Christie King,36,Female,Sales,Executive,9,PhD,San Francisco,165000
9997,9998,Alfred Keller,57,Male,Sales,Executive,30,PhD,New York,200000
9998,9999,Margaret Gomez,37,Female,Engineering,Manager,14,Master,New York,135000
9999,10000,Joan Sorensen,25,Female,Sales,Analyst,4,Bachelor,San Francisco,70000

In [6]:
df.groupby("Department")["Salary"].mean()

Department
Engineering     90680.332739
Finance        130376.175549
HR             126400.602410
Marketing      101734.571600
Product        116676.334107
Sales          127309.766327
Name: Salary, dtype: float64

In [8]:
pd.pivot_table(df, values="Salary", index="Department", aggfunc="mean")

                    Salary
Department
Engineering   90680.332739
Finance      130376.175549
HR           126400.602410
Marketing    101734.571600
Product      116676.334107
Sales        127309.766327