In [1]:
import pandas as pd
import scipy.stats as stats
import numpy as np

In [2]:
data = pd.read_csv('chi_dataset.csv')
data

    Gender Preference
0   Female        Tea
1   Female     Coffee
2     Male     Coffee
3     Male     Coffee
4   Female     Coffee
5     Male     Coffee
6     Male     Coffee
7   Female        Tea
8     Male     Coffee
9     Male        Tea
10  Female        Tea
11  Female     Coffee
12    Male        Tea
13    Male     Coffee
14  Female        Tea
15  Female     Coffee
16  Female        Tea
17  Female     Coffee
18    Male     Coffee
19  Female     Coffee
20  Female     Coffee
21    Male     Coffee
22  Female        Tea
23    Male        Tea
24  Female        Tea
25  Female     Coffee
26  Female        Tea
27    Male     Coffee
28    Male     Coffee
29  Female        Tea
30    Male        Tea
31    Male     Coffee
32    Male        Tea
33    Male     Coffee
34    Male     Coffee
35    Male     Coffee
36  Female     Coffee
37  Female     Coffee
38    Male        Tea
39  Female        Tea
40  Female     Coffee
41  Female     Coffee
42  Female        Tea
43    Male        Tea
44  Female     Coffee
45  Female        Tea
46    Male     Coffee
47    Male        Tea
48  Female     Coffee
49  Female        Tea
50  Female     Coffee
51  Female        Tea
52  Female        Tea
53  Female     Coffee
54    Male        Tea
55  Female     Coffee
56  Female        Tea
57    Male     Coffee
58    Male        Tea
59    Male     Coffee

In [3]:
table = pd.crosstab(data['Gender'], data['Preference'])
table

Preference  Coffee  Tea
Gender
Female          17   16
Male            17   10

In [4]:
obs = table.values
row_sum = obs.sum(axis = 1)
col_sum = obs.sum(axis = 0)
total = obs.sum()
obs

array([[17, 16],
       [17, 10]])

In [5]:
exp = np.outer(row_sum, col_sum) / total
exp

array([[18.7, 14.3],
       [15.3, 11.7]])

In [9]:
chi2 = ((obs - exp) ** 2 / exp).sum()
dof = (len(obs[0]) -1) * (len(obs) - 1)
print(chi2, dof)
chi,p,dof,exp1 = stats.chi2_contingency(table)
chi,dof,exp,exp1

0.7925407925407919 1

(0.39489921842862974,
 1,
 array([[18.7, 14.3],
        [15.3, 11.7]]),
 array([[18.7, 14.3],
        [15.3, 11.7]]))

In [13]:
p_v =  stats.chi2.sf(chi2, dof)
p_v,p

(0.6266670502614378, 0.529735340789638)