In [1]:
import matplotlib.pyplot as plt
import scipy.stats as stats
import seaborn as sns
import pandas as pd
import numpy as np

In [2]:
iris = sns.load_dataset('iris')
iris

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [3]:
iris['petal_length_cat'] = pd.cut(iris['petal_length'], bins = 3, labels = ['low', 'mid', 'high'])
iris

,sepal_length,sepal_width,petal_length,petal_width,species,petal_length_cat
0,5.1,3.5,1.4,0.2,setosa,low
1,4.9,3.0,1.4,0.2,setosa,low
2,4.7,3.2,1.3,0.2,setosa,low
3,4.6,3.1,1.5,0.2,setosa,low
4,5.0,3.6,1.4,0.2,setosa,low
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica,high
146,6.3,2.5,5.0,1.9,virginica,high
147,6.5,3.0,5.2,2.0,virginica,high
148,6.2,3.4,5.4,2.3,virginica,high
149,5.9,3.0,5.1,1.8,virginica,high

In [4]:
table = pd.crosstab(iris['petal_length_cat'], iris['species'])
table

species           setosa  versicolor  virginica
petal_length_cat
low                   50           0          0
mid                    0          48          6
high                   0           2         44

In [5]:
chi2, p, dof, exp = stats.chi2_contingency(table)
print('chi2', chi2, '\np_value', p, '\ndof', dof, '\nexpected', exp)

chi2 256.52173913043475
p_value 2.561410449304364e-54
dof 4
expected [[16.66666667 16.66666667 16.66666667]
 [18.         18.         18.        ]
 [15.33333333 15.33333333 15.33333333]]

In [6]:
obs = table.values
row_sums = obs.sum(axis = 1)
col_sums = obs.sum(axis = 0)
obs

array([[50,  0,  0],
       [ 0, 48,  6],
       [ 0,  2, 44]])

In [7]:
expect = np.outer(row_sums, col_sums) / obs.sum()
expect

array([[16.66666667, 16.66666667, 16.66666667],
       [18.        , 18.        , 18.        ],
       [15.33333333, 15.33333333, 15.33333333]])

In [8]:
chi2_man = ((obs - expect) ** 2 / expect).sum()
df = (len(obs[0]) - 1) * (len(obs) - 1)
print(chi2_man, df)

256.52173913043475 4

In [9]:
p_v = stats.chi2.sf(chi2_man, df)
p_v

2.561410449304364e-54

In [10]:
c = [20] * 5
c

[20, 20, 20, 20, 20]

In [11]:
df = sns.load_dataset('titanic').dropna(subset = ['age', 'fare'])
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [17]:
df[df['survived'] == 0][df['alive'] == 'no']

/tmp/ipykernel_3893/2082898687.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df['survived'] == 0][df['alive'] == 'no']

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
12,0,3,male,20.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
883,0,2,male,28.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True