In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv('/home/nihal_farooq_m/Bro_Files/Week 15/Datasets/EDA.csv')
df

,Age,Salary,Experience_Years,Department,Gender,Performance_Score,Satisfaction_Level
0,56,43141.0,17.0,HR,Male,2.06,0.58
1,46,105356.0,13.0,Operations,Male,2.44,0.48
2,32,96910.0,17.0,HR,Male,2.04,0.72
3,60,81044.0,1.0,Operations,Female,2.81,0.58
4,25,92214.0,21.0,IT,Female,1.13,0.67
...,...,...,...,...,...,...,...
145,30,73354.0,18.0,Finance,Female,4.36,0.31
146,49,27557.0,16.0,Operations,Female,1.36,0.28
147,56,63360.0,23.0,Marketing,Female,3.14,0.40
148,49,107018.0,18.0,Operations,Female,1.93,0.78
149,21,27200.0,22.0,IT,Female,2.37,0.67

In [6]:
df.groupby('Gender')['Salary'].mean()

Gender
Female    71532.366197
Male      74079.067568
Name: Salary, dtype: float64

In [7]:
df['rank'] = df.Experience_Years + df.Performance_Score + (df.Satisfaction_Level) * 5
df.head()

,Age,Salary,Experience_Years,Department,Gender,Performance_Score,Satisfaction_Level,rank
0,56,43141.0,17.0,HR,Male,2.06,0.58,21.96
1,46,105356.0,13.0,Operations,Male,2.44,0.48,17.84
2,32,96910.0,17.0,HR,Male,2.04,0.72,22.64
3,60,81044.0,1.0,Operations,Female,2.81,0.58,6.71
4,25,92214.0,21.0,IT,Female,1.13,0.67,25.48

AttributeError: 'function' object has no attribute 'sorted'