In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/home/nihal_farooq_m/Bro_Files/Week 15/Datasets/EDA.csv')
df

,Age,Salary,Experience_Years,Department,Gender,Performance_Score,Satisfaction_Level
0,56,43141.0,17.0,HR,Male,2.06,0.58
1,46,105356.0,13.0,Operations,Male,2.44,0.48
2,32,96910.0,17.0,HR,Male,2.04,0.72
3,60,81044.0,1.0,Operations,Female,2.81,0.58
4,25,92214.0,21.0,IT,Female,1.13,0.67
...,...,...,...,...,...,...,...
145,30,73354.0,18.0,Finance,Female,4.36,0.31
146,49,27557.0,16.0,Operations,Female,1.36,0.28
147,56,63360.0,23.0,Marketing,Female,3.14,0.40
148,49,107018.0,18.0,Operations,Female,1.93,0.78
149,21,27200.0,22.0,IT,Female,2.37,0.67

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Age                 150 non-null    int64
 1   Salary              145 non-null    float64
 2   Experience_Years    145 non-null    float64
 3   Department          150 non-null    object
 4   Gender              150 non-null    object
 5   Performance_Score   150 non-null    float64
 6   Satisfaction_Level  145 non-null    float64
dtypes: float64(4), int64(1), object(2)
memory usage: 8.3+ KB

In [3]:
df.describe()

,Age,Salary,Experience_Years,Performance_Score,Satisfaction_Level
count,150.000000,145.000000,145.000000,150.000000,145.000000
mean,40.866667,72832.062069,12.124138,2.932333,0.623379
std,13.836857,28065.301320,7.634791,1.127579,0.220247
min,18.000000,25854.000000,0.000000,1.010000,0.200000
25%,29.000000,48664.000000,5.000000,2.017500,0.470000
50%,41.000000,74811.000000,13.000000,2.955000,0.650000
75%,53.000000,94163.000000,19.000000,3.907500,0.790000
max,64.000000,119856.000000,24.000000,4.950000,1.000000

In [4]:
df.shape

(150, 7)

In [5]:
null = df.isna().sum()
print(null, null / len(df) * 100)

Age                   0
Salary                5
Experience_Years      5
Department            0
Gender                0
Performance_Score     0
Satisfaction_Level    5
dtype: int64 Age                   0.000000
Salary                3.333333
Experience_Years      3.333333
Department            0.000000
Gender                0.000000
Performance_Score     0.000000
Satisfaction_Level    3.333333
dtype: float64

In [9]:
for col in ['Salary', 'Experience_Years', 'Satisfaction_Level']:
    if col in df.columns:
        df[col].fillna(df[col].mean(), inplace = True)

/tmp/ipykernel_7449/3501673744.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mean(), inplace = True)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Age                 150 non-null    int64
 1   Salary              150 non-null    float64
 2   Experience_Years    150 non-null    float64
 3   Department          150 non-null    object
 4   Gender              150 non-null    object
 5   Performance_Score   150 non-null    float64
 6   Satisfaction_Level  150 non-null    float64
dtypes: float64(4), int64(1), object(2)
memory usage: 8.3+ KB

In [17]:
from sklearn.preprocessing import OneHotEncoder as ohe
from sklearn.preprocessing import LabelEncoder as le

In [ ]:
en = ohe.

In [19]:
df = pd.get_dummies(df, columns = ['Gender', 'Department'], drop_first = True)
df

,Age,Salary,Experience_Years,Performance_Score,Satisfaction_Level,Gender_Male,Department_HR,Department_IT,Department_Marketing,Department_Operations
0,56,43141.0,17.0,2.06,0.58,True,True,False,False,False
1,46,105356.0,13.0,2.44,0.48,True,False,False,False,True
2,32,96910.0,17.0,2.04,0.72,True,True,False,False,False
3,60,81044.0,1.0,2.81,0.58,False,False,False,False,True
4,25,92214.0,21.0,1.13,0.67,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...
145,30,73354.0,18.0,4.36,0.31,False,False,False,False,False
146,49,27557.0,16.0,1.36,0.28,False,False,False,False,True
147,56,63360.0,23.0,3.14,0.40,False,False,False,True,False
148,49,107018.0,18.0,1.93,0.78,False,False,False,False,True
149,21,27200.0,22.0,2.37,0.67,False,False,True,False,False

In [ ]:
scatter plot for exp and salary
correaltion heatmap for all numerical_cols